//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotEurobot2015 {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The Breakout TB10 module (not connected).</summary>
        private Gadgeteer.Modules.GHIElectronics.BreakoutTB10 breakoutTB10;
        
        /// <summary>The Display T35 module (not connected).</summary>
        private Gadgeteer.Modules.GHIElectronics.DisplayT35 displayT35;
        
        /// <summary>The Gyro module (not connected).</summary>
        private Gadgeteer.Modules.GHIElectronics.Gyro gyro;
        
        /// <summary>The RoboClaw module (not connected).</summary>
        private Gadgeteer.Modules.OrionRobotics.RoboClaw roboClaw;
        
        /// <summary>The Compass module (not connected).</summary>
        private Gadgeteer.Modules.GHIElectronics.Compass compass;
        
        /// <summary>The Accelerometer module (not connected).</summary>
        private Gadgeteer.Modules.GHIElectronics.Accelerometer accelerometer;
        
        /// <summary>The Bluetooth module (not connected).</summary>
        private Gadgeteer.Modules.GHIElectronics.Bluetooth bluetooth;
        
        /// <summary>The Breakout TB10 module (not connected).</summary>
        private Gadgeteer.Modules.GHIElectronics.BreakoutTB10 breakoutTB102;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZHydra Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZHydra)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZHydra();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            Microsoft.SPOT.Debug.Print("The module \'breakoutTB10\' was not connected in the designer and will be null.");
            Microsoft.SPOT.Debug.Print("The module \'displayT35\' was not connected in the designer and will be null.");
            Microsoft.SPOT.Debug.Print("The module \'gyro\' was not connected in the designer and will be null.");
            Microsoft.SPOT.Debug.Print("The module \'roboClaw\' was not connected in the designer and will be null.");
            Microsoft.SPOT.Debug.Print("The module \'compass\' was not connected in the designer and will be null.");
            Microsoft.SPOT.Debug.Print("The module \'accelerometer\' was not connected in the designer and will be null.");
            Microsoft.SPOT.Debug.Print("The module \'bluetooth\' was not connected in the designer and will be null.");
            Microsoft.SPOT.Debug.Print("The module \'breakoutTB102\' was not connected in the designer and will be null.");
        }
    }
}
