//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Braitenberg {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The Breakout TB10 module using socket 13 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.BreakoutTB10 BrkCapteurs;
        
        /// <summary>The RoboClaw module using socket 4 of the mainboard.</summary>
        private Gadgeteer.Modules.OrionRobotics.RoboClaw roboClaw;
        
        /// <summary>The Character Display module using socket 12 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.CharacterDisplay charDisplay;
        
        /// <summary>The USB Client DP module using socket 2 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.USBClientDP usbClientDP;
        
        /// <summary>The Button module using socket 11 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Button btn1;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZHydra Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZHydra)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZHydra();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.BrkCapteurs = new GTM.GHIElectronics.BreakoutTB10(13);
            this.roboClaw = new GTM.OrionRobotics.RoboClaw(4);
            this.charDisplay = new GTM.GHIElectronics.CharacterDisplay(12);
            this.usbClientDP = new GTM.GHIElectronics.USBClientDP(2);
            this.btn1 = new GTM.GHIElectronics.Button(11);
        }
    }
}
